### ISSUE TITLE
Feature/Scenario description can only be 1 line

### ISSUE THREAD

**Issue by incident-recipient** [cucumber-rs/gherkin#10]
One of the primary benefits of BDD is that it produces living documentation. This can be particularly effective when the gherkin is post-processed by something like AsciiDoctor to provide URLs, images, mathematical notation, etc in a convenient, easy to read and *useful* document.

However, unlike other parsers this one appears to crash if the descriptions for Features/Scenarios are more than one line long or have any whitespace

Steps to reproduce-> Use the following Gherkin
Feature: Living Documentation
Living documentation is used by may companies, including those with mission critical objectives such as healthcare. In these cases, the documentation is the source of truth and is central to the businesses operations.

Not being able to document or provide _mark up_ or other useful features limits the viability of what is supposed to be a source of truth.

Scenario: Adequate Description for core operations.
  We definitely want to be able to do this.

   Given I am writing living documentation
   And many levels of management, coworkers and others rely on it
   Then I need to have lengthier descriptions for features and scenarios

**Comment by bbqsrc** [comment]
This should now be fixed.

**Comment by incident-recipient** [comment]
This does not appear to be fixed. I was able to duplicate the issue by adding a multiline scenario to the test in the src code as well as existing rust projects now using the latest library.

Feature: Everything

Scenario: Nothing
  Given I just started

Scenario: Multiline
                Adding a multiline scenario when using the Feature files as input to generate documentation.

                There can be a lot of arbitary text and newlines but it shouldn't matter as long as one of the sentences doesn't start with a Gherkin keyword.
                Given I just started

**Comment by incident-recipient** [comment]
The issue seems to be with this rule in the new parser:
rule scenario() -> Scenario
    = _
      t:tags()
      _
      pa:position!()
      keyword((env.keywords().scenario)) ":" _ n:not_nl() _ nl_eof()  //Stop when we encounter a new line
      s:steps()?

My employer limits what I can contribute to open source projects. I'll see what I can do to help though.

**Comment by bbqsrc** [comment]
Ah, I misunderstood the issue. I'll look into it when I have time.

**Comment by incident-recipient** [comment]
Unfortunately I wasn't given clearance to contribute (not that I'm particularly proficient at rust yet anyway). 

But I think the solution will be along the answers of making a rule that says "newline followed by any whitespace followed by one of the 3 main gherkin keywords":

rule test_case_start() -> &'input str = n: $(nl() _ (env.keywords().given() / env.keywords().when() / env.keywords().then)) { n }
...
...
rule scenario() -> Scenario =  ....
....
keyword((env.keywords().scenario)) ":" _ n: !test_case_start()+


The above won't compile, but it can hopefully steer someone in the correct direction.

**Comment by bbqsrc** [comment]
Fixed in v0.8.4.

**Comment by bbqsrc** [comment]
0.8.4 was yanked due to causing other parsing issues.

**Comment by bbqsrc** [comment]
This is fixed in 0.9.0. Arbitrary descriptions below scenarios are not supported by the specification, and so are not included.

**Comment by incident-recipient** [comment]
It isn't obvious, but gherkin does support multi-line scenarios. 

Here is a multi-line test case out of the official mono-repository, which has been used to test other language implementations:
https://github.com/cucumber/cucumber/blob/master/gherkin/testdata/good/descriptions.feature

I think it would perhaps be worthwhile to move these official test cases to cucumber-rust/gherkin-rust as they would serve as a source of truth on how cucumber should behave (which ultimately is the point of the feature files anyway).

**Comment by bbqsrc** [comment]
Of course there's tests for something described absolutely nowhere. 

Supporting cucumber is seriously painful, haha.

**Comment by tyranron** [comment]
@ilslv is it still relevant?

**Comment by ilslv** [comment]
@tyranron yes, as only `Feature`s are allowed to have multi-line descriptions, while `Scenario`s doesn't even have `description` field yet.

**Comment by ilslv** [comment]
@tyranron yes, this issue should be fully covered.

**Comment by tyranron** [comment]
Released in [`gherkin` 0.12.0](https://crates.io/crates/gherkin/0.12.0) and [`cucumber` 0.13.0](https://crates.io/crates/cucumber/0.13.0).
