### ISSUE TITLE
`gherkin` doesn't allow to have both `Table` and `DocString` for a step

### ISSUE THREAD

**Issue by DDtKey** [cucumber-rs/gherkin#41]
Currently `gherkin::Step` may have both `Table` and `DocString` - it works pretty well, but turns out it's unfortunately disallowed by `gherkin` spec: https://github.com/cucumber/docs/issues/970

**Comment by tyranron** [comment]
@DDtKey thanks! I've read the original issue and see no point in fixing this. Being a superset here seems useful.

**Comment by DDtKey** [comment]
I personally don't mind, I find this a useful feature actually in some cases (described in the initial issue).

The only issue is impossibility to use linters and some formatting tools.

But totally understand the decision, even if it's deviation.

Thank you for the maintenance!
